# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
        migrations.AlterModelTable(
            name='measurement',
            table='measurement',
        ),
    ]
