# Generated by Django 4.2.16 on 2025-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(null=True, upload_to='templates/.2025-02-11.06-23-56'),
        ),
    ]
