# Generated by Django 4.2.16 on 2025-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(null=True, upload_to='templates/.2025-02-11.06-26-15'),
        ),
    ]
