# Generated by Django 4.2.16 on 2025-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(null=True, upload_to='templates/.2025-02-11.13-29-59'),
        ),
    ]
