# Generated by Django 4.2.16 on 2025-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
