# Generated by Django 4.2.16 on 2025-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_template_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='slug_title',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
