# Generated by Django 4.2.16 on 2024-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nocapitelni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='nocapitelni', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Nocapitelni',
                'verbose_name_plural': 'Nocapitelni',
            },
        ),
    ]
