# Generated by Django 4.2.16 on 2025-04-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
