# Generated by Django 4.2.16 on 2025-04-02 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.object_passport.models.object_gallery


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object_passport', '0002_rename_longtitude_object_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.apps.object_passport.models.object_gallery.upload_object_files, verbose_name='Rasm yoki Video')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object', verbose_name='Obyekt nomi')),
            ],
            options={
                'verbose_name': 'Object Gallery',
                'verbose_name_plural': 'Objects Gallery',
                'db_table': 'object_gallery',
                'ordering': ('-id',),
            },
        ),
    ]
