# Generated by Django 4.2.16 on 2025-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik'),
        ),
    ]
