# Generated by Django 4.2.16 on 2025-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0004_alter_object_latitude_alter_object_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Uzunlik'),
        ),
    ]
