# Generated by Django 4.2.16 on 2025-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0005_alter_object_latitude_alter_object_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fayl turi'),
        ),
    ]
