# Generated by Django 4.2.16 on 2025-04-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0006_gallery_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hajmi'),
        ),
    ]
