# Generated by Django 4.2.16 on 2025-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0007_gallery_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category_type',
            field=models.CharField(blank=True, choices=[('amalga_oshirilayotgan_loyihalar', 'Amalga oshirilayotgan loyihalar'), ('istiqbolli_loyihalara', 'Istiqbolli loyihalar'), ('qurilishi_yakunlangan_loyihalar', 'Qurilishi yakunlangan loyihalar')], default='istiqbolli_loyihalara', max_length=255, null=True),
        ),
    ]
