# Generated by Django 4.2.16 on 2025-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0008_object_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category_type',
        ),
        migrations.AddField(
            model_name='object',
            name='status_type',
            field=models.CharField(blank=True, choices=[('Istiqbolli loyihalar', 'New'), ('Amalga oshirilayotgan loyihalar', 'In progress'), ('Qurilishi yakunlangan loyihalar', 'Completed')], default='Istiqbolli loyihalar', max_length=255, null=True),
        ),
    ]
