# Generated by Django 4.2.16 on 2025-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0009_remove_object_category_type_object_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='status_type',
            field=models.CharField(blank=True, choices=[('new', 'Istiqbolli loyihalar'), ('in_progress', 'Amalga oshirilayotgan loyihalar'), ('completed', 'Qurilishi yakunlangan loyihalar')], default='new', max_length=255, null=True),
        ),
    ]
