# Generated by Django 4.2.16 on 2025-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0010_alter_object_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Obyekt kodi'),
        ),
    ]
