# Generated by Django 4.2.16 on 2025-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0002_remove_employeecommunication_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecommunication',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecommunication',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecommunication',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemessage',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
