# Generated by Django 4.2.16 on 2025-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0003_employeecommunication_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunication',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('done', 'Done'), ('in confirmation', 'In confirmation'), ('in progress', 'In progress'), ('incomplete', 'Incomplete'), ('completed late', 'Completed late')], default='new', max_length=255, null=True),
        ),
    ]
