# Generated by Django 4.2.16 on 2025-04-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0007_gallery_size'),
        ('employee_communication', '0003_employeecommunication_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecommunication',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object'),
        ),
        migrations.AlterField(
            model_name='employeecommunication',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('done', 'Done'), ('in confirmation', 'In confirmation'), ('in progress', 'In progress'), ('incomplete', 'Incomplete'), ('completed late', 'Completed late')], default='new', max_length=255, null=True),
        ),
    ]
