# Generated by Django 4.2.16 on 2025-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0004_employeecommunication_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecommunication',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='employeecommunication',
            name='object_id',
        ),
        migrations.AddField(
            model_name='employeecommunication',
            name='section_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
