# Generated by Django 4.2.16 on 2025-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0005_remove_employeecommunication_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunication',
            name='section_type',
            field=models.CharField(blank=True, choices=[('construction work', 'Construction work'), ('project document', 'Project document'), ('equipment', 'Equipment'), ('accounting', 'Accounting')], max_length=255, null=True),
        ),
    ]
