# Generated by Django 4.2.16 on 2025-04-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0004_alter_employeecommunication_status'),
        ('employee_communication', '0006_alter_employeecommunication_section_type'),
    ]

    operations = [
    ]
