# Generated by Django 4.2.16 on 2025-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_communication', '0007_merge_20250409_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunication',
            name='section_type',
            field=models.CharField(blank=True, choices=[('construction_work', 'Construction work'), ('project_document', 'Project document'), ('equipment', 'Equipment'), ('accounting', 'Accounting')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeecommunication',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('done', 'Done'), ('in_confirmation', 'In confirmation'), ('in_progress', 'In progress'), ('incomplete', 'Incomplete'), ('completed_late', 'Completed late')], default='new', max_length=255, null=True),
        ),
    ]
