# Generated by Django 4.2.16 on 2025-04-17 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_communication', '0008_alter_employeecommunication_section_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecommunication',
            name='employee',
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_communication.employeecommunication')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('communication', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='employeecommunication',
            name='worker',
            field=models.ManyToManyField(related_name='worker_assigned', through='employee_communication.EmployeeCommunicationRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
