# Generated by Django 4.2.16 on 2025-04-17 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_communication', '0009_remove_employeecommunication_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecommunication',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='employeecommunication',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='employeecommunication',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='employeecommunication',
            name='worker',
        ),
        migrations.AddField(
            model_name='employeecommunication',
            name='employee',
            field=models.ManyToManyField(related_name='employee_assigned', through='employee_communication.EmployeeCommunicationRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
