# Generated by Django 4.2.16 on 2025-04-17 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object_passport', '0007_gallery_size'),
        ('employee_communication', '0010_remove_employeecommunication_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunication',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object', verbose_name='Obyekt nomi'),
        ),
        migrations.AlterField(
            model_name='employeecommunication',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AlterField(
            model_name='employeecommunication',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_file_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_text_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
    ]
