# Generated by Django 4.2.16 on 2025-04-18 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_communication', '0011_alter_employeecommunication_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeecommunication',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_assigned', through='employee_communication.EmployeeCommunicationRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
