# Generated by Django 4.2.16 on 2025-04-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_communication', '0012_alter_employeecommunication_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommunicationrecipient',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
