# Generated by Django 4.2.16 on 2025-01-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
            ],
            options={
                'verbose_name': 'Dashboard Button',
                'verbose_name_plural': 'Asosiy Knopkalar',
            },
        ),
        migrations.CreateModel(
            name='DashboardCategoryButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('dashboard_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardbutton', verbose_name='Kinopka')),
            ],
            options={
                'verbose_name': 'Dashboard Category Button',
                'verbose_name_plural': 'Kategoriya Knopkalar',
            },
        ),
        migrations.CreateModel(
            name='DashboardSubCategoryButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('dashboard_category_btn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardcategorybutton', verbose_name='Categoriya knopka')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Dashboard Sub Category Button',
                'verbose_name_plural': 'Obyekt nomlari',
            },
        ),
        migrations.CreateModel(
            name='NextStageDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('is_forma', models.BooleanField(default=False, verbose_name='Forma')),
                ('is_section', models.BooleanField(default=False, verbose_name="Bo'lim")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Keyingi hujjat',
                'verbose_name_plural': 'Loyiha hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='ProjectSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirigan vaqti")),
                ('next_stage_documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nextstagedocuments', verbose_name='Keyingi hujjat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Loyiha bo'limi",
                'verbose_name_plural': "Loyiha Bo'limlar 2",
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('is_obj_password', models.BooleanField(default=False, verbose_name='Obyekt pasporti?')),
                ('is_project_doc', models.BooleanField(default=False, verbose_name='Loyiha hujjatlari?')),
                ('is_work_smr', models.BooleanField(default=False, verbose_name='Qurilish montaj ishlari hujjatlari?')),
                ('is_equipment', models.BooleanField(default=False, verbose_name='Uskunalar hujjatlari?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('subcategories_btn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdocumentation', to='dashboard.dashboardsubcategorybutton', verbose_name='Loyiha nomi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Loyiha hujjati',
                'verbose_name_plural': "Loyiha Bo'limlar 1",
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='project_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectdocumentation', verbose_name='Loyiha hujjatlar'),
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='subcategories_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardsubcategorybutton', verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nomi')),
                ('calendar', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hujjat sanasi')),
                ('file_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hujjat Kodi')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='files/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nextstagedocuments', verbose_name='Loyiha hujjatlar')),
                ('project_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectsections', verbose_name="Loyiha bo'limi")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
            },
        ),
    ]
