# Generated by Django 4.2.16 on 2025-01-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboardbutton_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextstagedocuments',
            name='project_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='dashboard.projectdocumentation', verbose_name='Loyiha hujjatlar'),
        ),
    ]
