# Generated by Django 4.2.16 on 2025-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_nextstagedocuments_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstagedocuments',
            name='is_file',
            field=models.BooleanField(default=False, verbose_name='Fayl yuklash'),
        ),
    ]
