# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_nextstagedocuments_is_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdocumentation',
            options={'ordering': ('-id',), 'verbose_name': 'Loyiha hujjati', 'verbose_name_plural': "Loyiha Bo'limlar 1"},
        ),
        migrations.AlterModelTable(
            name='dashboardbutton',
            table='dashboard_button',
        ),
        migrations.AlterModelTable(
            name='dashboardcategorybutton',
            table='dashboard_category_button',
        ),
        migrations.AlterModelTable(
            name='dashboardsubcategorybutton',
            table='dashboard_subcategory_button',
        ),
        migrations.AlterModelTable(
            name='files',
            table='dashboard_files',
        ),
        migrations.AlterModelTable(
            name='nextstagedocuments',
            table='next_stage_documents',
        ),
        migrations.AlterModelTable(
            name='projectdocumentation',
            table='project_documentation',
        ),
        migrations.AlterModelTable(
            name='projectsections',
            table='project_sections',
        ),
    ]
