# Generated by Django 4.2.16 on 2025-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_projectdocumentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbutton',
            name='slug_name',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
