# Generated by Django 4.2.16 on 2025-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboardbutton_slug_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Obyekt nomlari',
                'db_table': 'object',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('slug_name', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ObjectCategory',
                'verbose_name_plural': 'Asosiy Knopkalar',
                'db_table': 'boject_category',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ObjectSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Object SubCategory',
                'verbose_name_plural': 'Kategoriya Knopkalar',
                'db_table': 'object_subcategory',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='dashboardbutton',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboardbutton',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='dashboardcategorybutton',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboardcategorybutton',
            name='dashboard_button',
        ),
        migrations.RemoveField(
            model_name='dashboardcategorybutton',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='dashboardsubcategorybutton',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboardsubcategorybutton',
            name='dashboard_category_btn',
        ),
        migrations.RemoveField(
            model_name='dashboardsubcategorybutton',
            name='deleted_by',
        ),
    ]
