# Generated by Django 4.2.16 on 2025-02-11 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_objectspassword_category_btn_and_more'),
        ('dashboard', '0007_object_objectcategory_objectsubcategory_and_more'),
        ('equipment', '0007_alter_hydrostation_dashboard_subbtn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardButton',
        ),
        migrations.DeleteModel(
            name='DashboardCategoryButton',
        ),
        migrations.AddField(
            model_name='objectsubcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectsubcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectsubcategory',
            name='object_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectcategory', verbose_name='Kinopka'),
        ),
        migrations.AddField(
            model_name='objectcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='object_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectsubcategory', verbose_name='Categoriya knopka'),
        ),
        migrations.AlterField(
            model_name='nextstagedocuments',
            name='subcategories_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object', verbose_name='Loyiha nomi'),
        ),
        migrations.AlterField(
            model_name='projectdocumentation',
            name='subcategories_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdocumentation', to='dashboard.object', verbose_name='Loyiha nomi'),
        ),
        migrations.DeleteModel(
            name='DashboardSubCategoryButton',
        ),
    ]
