# Generated by Django 4.2.16 on 2025-02-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_dashboardbutton_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objectcategory',
            table='object_category',
        ),
    ]
