# Generated by Django 4.2.16 on 2025-02-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_objectcategory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='object',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qurilish tuganlangan vaqti'),
        ),
        migrations.AddField(
            model_name='object',
            name='equipment_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='object',
            name='investment_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='object',
            name='object_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectcategory', verbose_name='Asosiy knopkalar'),
        ),
        migrations.AddField(
            model_name='object',
            name='project_documentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectdocumentation', verbose_name="Obyekt bo'limi"),
        ),
        migrations.AddField(
            model_name='object',
            name='smr_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='object',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qurilish boshlangan vaqti'),
        ),
        migrations.AddField(
            model_name='object',
            name='total_power',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Umumiy quvvat'),
        ),
        migrations.AddField(
            model_name='object',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='object',
            name='uge_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
    ]
