# Generated by Django 4.2.16 on 2025-02-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_name_object_title_object_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextstagedocuments',
            old_name='subcategories_btn',
            new_name='object',
        ),
    ]
