# Generated by Django 4.2.16 on 2025-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_subcategories_btn_nextstagedocuments_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextstagedocuments',
            name='project_document',
        ),
    ]
