# Generated by Django 4.2.16 on 2025-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_documentfiles_delete_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfiles',
            name='calendar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='file_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='document_files/'),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
