# Generated by Django 4.2.16 on 2025-02-24 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_documentfiles_calendar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfiles',
            options={'ordering': ('-id',), 'verbose_name': 'Docuemtn File', 'verbose_name_plural': 'Document Files'},
        ),
        migrations.AlterModelOptions(
            name='nextstagedocuments',
            options={'ordering': ('-id',), 'verbose_name': 'Next Stage Document', 'verbose_name_plural': 'Next Stage Documents'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('-id',), 'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='objectcategory',
            options={'ordering': ('-id',), 'verbose_name': 'Object Category', 'verbose_name_plural': 'Object Categories'},
        ),
        migrations.AlterModelOptions(
            name='objectsubcategory',
            options={'ordering': ('-id',), 'verbose_name': 'Object SubCategory', 'verbose_name_plural': 'Object SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='projectsections',
            options={'ordering': ('-id',), 'verbose_name': 'Project Section', 'verbose_name_plural': 'Project Sections'},
        ),
        migrations.AddField(
            model_name='documentfiles',
            name='project_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectsections', verbose_name='Project Section'),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nextstagedocuments', verbose_name='Next Stage Document'),
        ),
    ]
