# Generated by Django 4.2.16 on 2025-02-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_documentfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdocumentation',
            options={'ordering': ('-id',), 'verbose_name': 'Project Documentation', 'verbose_name_plural': 'Project Documentations'},
        ),
    ]
