# Generated by Django 4.2.16 on 2025-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_projectdocumentation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentfiles',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nextstagedocuments',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projectdocumentation',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projectsections',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi'),
        ),
    ]
