# Generated by Django 4.2.16 on 2025-03-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_section_constructionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='equipment_price',
            new_name='construction_work_amount',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='investment_price',
            new_name='equipment_amount',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='smr_price',
            new_name='other_expense',
        ),
        migrations.RemoveField(
            model_name='object',
            name='total_power',
        ),
        migrations.RemoveField(
            model_name='object',
            name='uge_price',
        ),
        migrations.AddField(
            model_name='object',
            name='object_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='pressure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='water_consumption',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectcategory', verbose_name='Obyekt Categoriya'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectsubcategory', verbose_name='Obyekt Subcategoriya'),
        ),
    ]
