# Generated by Django 4.2.16 on 2025-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_equipment_price_object_construction_work_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='object_file',
            field=models.FileField(null=True, upload_to='object_files/'),
        ),
    ]
