# Generated by Django 4.2.16 on 2025-03-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_template_is_active'),
        ('dashboard', '0020_object_object_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
    ]
