# Generated by Django 4.2.16 on 2025-03-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_object_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='community_fund',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='object',
            name='foreign_loan',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
    ]
