# Generated by Django 4.2.16 on 2025-03-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_object_community_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Bosim'),
        ),
        migrations.AlterField(
            model_name='object',
            name='water_consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Suv sarfi'),
        ),
    ]
