# Generated by Django 4.2.16 on 2025-03-07 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_template_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0024_alter_object_pressure_alter_object_water_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionInstallationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('file_code', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='document_files/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Installation File',
                'verbose_name_plural': 'Construction Installation Files',
                'db_table': 'installation_file',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Installation Project',
                'verbose_name_plural': 'Construction Installation Projects',
                'db_table': 'construction_installation_project',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('is_forma', models.BooleanField(default=False, verbose_name='Forma')),
                ('is_file', models.BooleanField(default=False, verbose_name='Fayl yuklash')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object', verbose_name='Loyiha nomi')),
            ],
            options={
                'verbose_name': 'Construction Installation Section',
                'verbose_name_plural': 'Construction Installation Sections',
                'db_table': 'construction_installation_section',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('installation_work_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('date', models.DateField(blank=True, null=True)),
                ('remanied_work_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('cost_of_performed_work', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contract_files/')),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_installation_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationsection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Installation Statistics',
                'verbose_name_plural': 'Construction Installation Statistics',
                'db_table': 'construction_installation_statistics',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('construction_installation_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationsection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Installation SubSection',
                'verbose_name_plural': 'Construction Installation SubSections',
                'db_table': 'sub_section',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyCompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('construction_installation_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationproject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Completed Task',
                'verbose_name_plural': 'Monthly Completed Tasks',
                'db_table': 'monthly_completed_task',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='object',
        ),
        migrations.DeleteModel(
            name='ConstructionFile',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='constructioninstallationproject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationsubsection'),
        ),
        migrations.AddField(
            model_name='constructioninstallationfile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationsubsection'),
        ),
    ]
