# Generated by Django 4.2.16 on 2025-03-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_constructioninstallationfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructioninstallationstatistics',
            name='construction_installation_section',
        ),
        migrations.AddField(
            model_name='constructioninstallationstatistics',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object'),
        ),
    ]
