# Generated by Django 4.2.16 on 2025-03-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_constructioninstallationstatistics_construction_installation_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructioninstallationproject',
            old_name='section',
            new_name='sub_section',
        ),
        migrations.AlterField(
            model_name='monthlycompletedtask',
            name='construction_installation_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_tasks', to='dashboard.constructioninstallationproject'),
        ),
    ]
