# Generated by Django 4.2.16 on 2025-03-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_constructioninstallationproject_sub_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructioninstallationfile',
            old_name='section',
            new_name='sub_section',
        ),
    ]
