# Generated by Django 4.2.16 on 2025-03-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_rename_section_constructioninstallationfile_sub_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructioninstallationfile',
            name='sub_section',
        ),
        migrations.AddField(
            model_name='constructioninstallationfile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.constructioninstallationsection'),
        ),
        migrations.DeleteModel(
            name='ConstructionInstallationSubSection',
        ),
    ]
