# Generated by Django 4.2.16 on 2025-03-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_constructioninstallationfile_sub_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructioninstallationfile',
            name='full_name',
        ),
    ]
