# Generated by Django 4.2.16 on 2025-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_constructioninstallationfile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='annual_electricity_production',
            field=models.FloatField(blank=True, null=True, verbose_name='Yillik elektr ishlab chiqarish'),
        ),
    ]
