# Generated by Django 4.2.16 on 2025-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_object_annual_electricity_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_file',
            field=models.FileField(blank=True, null=True, upload_to='object_files/', verbose_name='Obyekt pasporti fayli'),
        ),
    ]
