# Generated by Django 4.2.16 on 2025-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_object_object_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_power',
            field=models.FloatField(blank=True, null=True, verbose_name='Obyetk umumiy quvvati'),
        ),
    ]
