# Generated by Django 4.2.16 on 2025-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_object_object_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioninstallationfile',
            name='file_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
