# Generated by Django 4.2.16 on 2025-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_constructioninstallationfile_file_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_file',
            field=models.FileField(blank=True, null=True, upload_to='object_files/'),
        ),
    ]
