# Generated by Django 4.2.16 on 2025-03-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_object_object_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
