# Generated by Django 4.2.16 on 2025-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_remove_object_project_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='object',
            name='useful_work_coefficient',
            field=models.FloatField(blank=True, max_length=30, null=True, verbose_name='Foydali ish koeffitsiyenti'),
        ),
    ]
