# Generated by Django 4.1.5 on 2024-12-18 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_remove_checklist_equipment_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('subject_of_contract', models.TextField(blank=True, null=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('date', models.DateField()),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.checklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
