# Generated by Django 4.1.5 on 2024-11-27 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.account.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activating_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ActivationSMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_sent_time', models.CharField(blank=True, default=main.apps.account.utils.otp_expire_time, max_length=100, null=True)),
                ('otp_sent_time_reset', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ActivationSMSCodes',
                'ordering': ['-id'],
            },
        ),
    ]
