# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_department_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
