# Generated by Django 4.2.16 on 2025-02-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_department_table_alter_position_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/.2025-02-10.06-05-54'),
        ),
    ]
