# Generated by Django 4.2.16 on 2025-03-19 06:31

from django.db import migrations, models
import main.apps.account.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.account.models.user.upload_profile_images),
        ),
    ]
