version: '3'

volumes:
  static_volume:
  media_volume:
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: proclear_django_prod
    container_name: django_prod
    networks:
      - django_network
    volumes:
      - .:/app:cached
      - static_volume:/home/app/web/main/static
      - media_volume:/home/app/web/main/media
    env_file:
      - ./.envs/.production/.django
    ports:
      - "8001:8000"
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: proclear_nginx_prod
    container_name: nginx_prod
    networks:
      - django_network
    volumes:
      - static_volume:/home/app/web/main/static
      - media_volume:/home/app/web/main/media
    ports:
      - "8001:8001"
    depends_on:
      - django

networks:
  django_network: