version: '3.8'

volumes:
  static_volume:
  media_volume:
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gidro_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
      - static_volume:/home/app/web/main/static
      - media_volume:/home/app/web/main/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gidro_postgres
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:cached
      - production_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: gidro_nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/main/static
      - media_volume:/home/app/web/main/media
    ports:
      - 8080:80
      - 777:777
    depends_on:
      - django

