# Generated by Django 4.2.16 on 2025-01-27 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reestr', '0006_remove_year_created_by_remove_year_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('additional_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('delivery_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reestr.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hydro Station',
                'verbose_name_plural': 'Hydro Stations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FinancialResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('prepayment_from_own_fund', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('prepayment_from_foreign_credit_account', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('additional_prepayment', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('payment_on_completion', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('hydro_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.hydrostation')),
            ],
            options={
                'verbose_name': 'Financial Resource',
                'verbose_name_plural': 'Financial Resources',
                'ordering': ('-id',),
            },
        ),
    ]
