# Generated by Django 4.2.16 on 2025-04-01 05:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.equipment.models.hydro_station


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object_passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('has_subcategories', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'db_table': 'equipment_category',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Equipment SubCategory',
                'verbose_name_plural': 'Equipment SubCategories',
                'db_table': 'equipment_subcategory',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IndustrialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('delivered_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='created', max_length=20, verbose_name='Holati')),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory')),
                ('equipment_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentsubcategory')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.measurement')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object')),
            ],
            options={
                'verbose_name': 'Industrial Asset',
                'verbose_name_plural': 'Industrial Assets',
                'db_table': 'industrial_asset',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HydroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.apps.equipment.models.hydro_station.upload_hydro_station_files)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('calculation_type', models.CharField(choices=[('amount', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=255)),
                ('financial_reource_type', models.CharField(choices=[('funds', 'Funds'), ('ges', 'Ges')], default='funds', max_length=255)),
                ('prepayment_from_own_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('prepayment_from_foreign_credit_account', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('additional_prepayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('payment_on_completion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('transit_equipment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('delivery_date', models.DateField()),
                ('financial_resource_data', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object')),
            ],
            options={
                'verbose_name': 'Hydro Station',
                'verbose_name_plural': 'Hydro Stations',
                'db_table': 'hydro_station',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='hydro_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.hydrostation'),
        ),
    ]
