# Generated by Django 4.2.16 on 2025-01-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_nextstagedocuments_is_file'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrostation',
            name='title',
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='dashboard_subbtn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardsubcategorybutton'),
        ),
    ]
