# Generated by Django 4.2.16 on 2025-01-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('equipment', '0002_remove_hydrostation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrostation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
    ]
