# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_rename_commodity_code_industrialasset_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialresource',
            table='financial_resource',
        ),
        migrations.AlterModelTable(
            name='hydrostation',
            table='hydro_station',
        ),
        migrations.AlterModelTable(
            name='industrialasset',
            table='industrial_asset',
        ),
        migrations.AlterModelTable(
            name='industrialequipment',
            table='industrial_equipment',
        ),
    ]
