# Generated by Django 4.2.16 on 2025-02-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_object_objectcategory_objectsubcategory_and_more'),
        ('equipment', '0006_alter_financialresource_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrostation',
            name='dashboard_subbtn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object'),
        ),
    ]
