# Generated by Django 4.2.16 on 2025-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_hydrostation_dashboard_subbtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialasset',
            name='status',
            field=models.CharField(choices=[('yaratildi', 'Yaratildi'), ('yolda', "Yo'lda"), ('yetib_keldi', 'Yetib keldi')], default='yaratildi', max_length=20, verbose_name='Holati'),
        ),
    ]
