# Generated by Django 4.2.16 on 2025-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_industrialasset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrostation',
            old_name='additional_amount',
            new_name='transit_equipment_amount',
        ),
        migrations.RemoveField(
            model_name='industrialasset',
            name='status',
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/.2025-02-13.06-13-59'),
        ),
        migrations.AddField(
            model_name='industrialequipment',
            name='status',
            field=models.CharField(choices=[('yaratildi', 'Created'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='yaratildi', max_length=20, verbose_name='Holati'),
        ),
    ]
