# Generated by Django 4.2.16 on 2025-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_rename_additional_amount_hydrostation_transit_equipment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialequipment',
            name='status',
        ),
        migrations.AddField(
            model_name='industrialasset',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='created', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='hydrostation',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/.2025-02-13.12-37-10'),
        ),
    ]
