# Generated by Django 4.2.16 on 2025-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_remove_industrialequipment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrostation',
            old_name='dashboard_subbtn',
            new_name='object',
        ),
        migrations.AlterField(
            model_name='hydrostation',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/.2025-02-13.12-44-04'),
        ),
    ]
