# Generated by Django 4.2.16 on 2025-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_hydrostation_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrostation',
            name='contract_file',
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='file',
            field=models.FileField(null=True, upload_to='contract_files/'),
        ),
    ]
