# Generated by Django 4.2.16 on 2025-02-19 07:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_name_object_title_object_end_date_and_more'),
        ('equipment', '0015_remove_hydrostation_contract_file_hydrostation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialresource',
            name='additional_prepayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='financialresource',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='financialresource',
            name='payment_on_completion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='financialresource',
            name='prepayment_from_foreign_credit_account',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='financialresource',
            name='prepayment_from_own_fund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='hydrostation',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AlterField(
            model_name='hydrostation',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object'),
        ),
        migrations.AlterField(
            model_name='hydrostation',
            name='transit_equipment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
    ]
