# Generated by Django 4.2.16 on 2025-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_hydrostation_additional_prepayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrostation',
            name='financial_resource_title',
        ),
        migrations.RemoveField(
            model_name='hydrostation',
            name='percent',
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='calculation_type',
            field=models.CharField(choices=[('amount', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='financial_resource_data',
            field=models.JSONField(default=dict),
        ),
    ]
