# Generated by Django 4.2.16 on 2025-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_remove_hydrostation_financial_resource_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrostation',
            name='financial_resource_data',
            field=models.JSONField(default=list),
        ),
    ]
