# Generated by Django 4.2.16 on 2025-02-28 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0019_alter_hydrostation_financial_resource_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('hydro_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.hydrostation')),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'db_table': 'equipment_category',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Equipment SubCategory',
                'verbose_name_plural': 'Equipment SubCategories',
                'db_table': 'equipment_subcategory',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='industrialasset',
            name='industrial_equipment',
        ),
        migrations.DeleteModel(
            name='IndustrialEquipment',
        ),
        migrations.AddField(
            model_name='industrialasset',
            name='equipment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='industrialasset',
            name='equipment_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentsubcategory'),
        ),
    ]
