# Generated by Django 4.2.16 on 2025-03-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_alter_industrialasset_delivered_in_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialasset',
            name='delivered_in_percent',
        ),
        migrations.RemoveField(
            model_name='industrialasset',
            name='expected_amount',
        ),
        migrations.RemoveField(
            model_name='industrialasset',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='industrialasset',
            name='remaining_in_percent',
        ),
    ]
