# Generated by Django 4.2.16 on 2025-03-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_remove_industrialasset_delivered_in_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialasset',
            name='equipment_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentsubcategory'),
        ),
    ]
