# Generated by Django 4.2.16 on 2025-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_alter_industrialasset_equipment_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='has_subcategories',
            field=models.BooleanField(default=False),
        ),
    ]
