# Generated by Django 4.2.16 on 2025-03-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_alter_equipmentsubcategory_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsubcategory',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory'),
        ),
    ]
