# Generated by Django 4.2.16 on 2025-03-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_template_is_active'),
        ('equipment', '0028_alter_equipmentsubcategory_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialasset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
    ]
