# Generated by Django 4.2.16 on 2025-03-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_object_community_fund_and_more'),
        ('equipment', '0029_industrialasset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialasset',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object'),
        ),
    ]
