# Generated by Django 4.2.16 on 2025-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0030_industrialasset_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrostation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/'),
        ),
    ]
