# Generated by Django 4.2.16 on 2025-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_alter_hydrostation_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialResource',
        ),
    ]
