# Generated by Django 4.2.16 on 2025-03-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_delete_financialresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialasset',
            name='currency',
        ),
    ]
