# Generated by Django 4.2.16 on 2025-03-19 06:31

from django.db import migrations, models
import main.apps.equipment.models.hydro_station


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_remove_industrialasset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrostation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.apps.equipment.models.hydro_station.upload_hydro_station_files),
        ),
    ]
