# Generated by Django 4.2.16 on 2025-01-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Ish nomi')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Umumiy xarajat summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilish ishlari',
                'verbose_name_plural': 'Qurilish ishlari',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Oy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oy',
                'verbose_name_plural': 'Oylar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yil',
                'verbose_name_plural': 'Yillar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='Sarflangan summa')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Miqdori')),
                ('total_year', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Jami yil summa')),
                ('total_fact', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Jami fakt summa')),
                ('total_fact_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Jami fakt summa')),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Farq summa')),
                ('total_difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Jami Farq summa')),
                ('construction_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_construction_task', to='reestr.constructiontask', verbose_name='Qurilish ishlari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_expenses', to='reestr.month', verbose_name='Oy')),
                ('year', models.ManyToManyField(blank=True, related_name='monthly_expenses', to='reestr.year', verbose_name='Yil')),
            ],
            options={
                'verbose_name': 'Qurilish ishlari',
                'verbose_name_plural': 'Qurilish ishlari',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='months', to='reestr.year', verbose_name='Yil'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name="O'lchov nomi")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='constructiontask',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reestr.currency'),
        ),
        migrations.AddField(
            model_name='constructiontask',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constructiontask',
            name='employee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
    ]
