# Generated by Django 4.2.16 on 2025-01-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='title',
        ),
    ]
