# Generated by Django 4.2.16 on 2025-01-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('reestr', '0002_rename_year_year_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiontask',
            options={'ordering': ('-id',), 'verbose_name': 'Construction Task', 'verbose_name_plural': 'Construction Tasks'},
        ),
        migrations.AlterModelOptions(
            name='monthlyexpense',
            options={'ordering': ('-id',), 'verbose_name': 'Monthly Expense', 'verbose_name_plural': 'Monthly Expenses'},
        ),
        migrations.AddField(
            model_name='constructiontask',
            name='next_stage_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nextstagedocuments'),
        ),
    ]
