# Generated by Django 4.2.16 on 2025-01-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0005_alter_constructiontask_next_stage_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='year',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
