# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0007_alter_constructiontask_currency_delete_currency'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='constructiontask',
            table='construction_task',
        ),
        migrations.AlterModelTable(
            name='monthlyexpense',
            table='monthly_expense',
        ),
    ]
