# Generated by Django 4.2.16 on 2025-04-01 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.construction_work.models.file
import main.apps.construction_work.models.statistics


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object_passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionInstallationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Installation Project',
                'verbose_name_plural': 'Construction Installation Projects',
                'db_table': 'construction_installation_project',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyCompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('construction_installation_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_tasks', to='construction_work.constructioninstallationproject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Completed Task',
                'verbose_name_plural': 'Monthly Completed Tasks',
                'db_table': 'monthly_completed_task',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('installation_work_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('date', models.DateField(blank=True, null=True)),
                ('remanied_work_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('cost_of_performed_work', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to=main.apps.construction_work.models.statistics.upload_contract_files)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object')),
            ],
            options={
                'verbose_name': 'Construction Installation Statistics',
                'verbose_name_plural': 'Construction Installation Statistics',
                'db_table': 'construction_installation_statistics',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionInstallationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('is_forma', models.BooleanField(default=False, verbose_name='Forma')),
                ('is_file', models.BooleanField(default=False, verbose_name='Fayl yuklash')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object', verbose_name='Loyiha nomi')),
            ],
            options={
                'verbose_name': 'Construction Installation Section',
                'verbose_name_plural': 'Construction Installation Sections',
                'db_table': 'construction_installation_section',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='constructioninstallationproject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction_work.constructioninstallationsection'),
        ),
        migrations.CreateModel(
            name='ConstructionInstallationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('file_code', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.apps.construction_work.models.file.upload_construction_installation_files)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction_work.constructioninstallationsection')),
            ],
            options={
                'verbose_name': 'Construction Installation File',
                'verbose_name_plural': 'Construction Installation Files',
                'db_table': 'installation_file',
                'ordering': ('-id',),
            },
        ),
    ]
