# Generated by Django 4.2.16 on 2025-04-17 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction_work', '0002_worktype_workcategory_monthlyworkvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('plan', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('fact', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction_work.workcategory')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction_work.worktype')),
            ],
            options={
                'verbose_name': 'Work Volume',
                'verbose_name_plural': 'Work Volumes',
                'db_table': 'work_volume',
                'ordering': ('-id',),
            },
        ),
    ]
