# Generated by Django 4.2.16 on 2025-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_work', '0003_workvolume'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monthlyworkvolume',
            constraint=models.UniqueConstraint(fields=('work_category', 'work_type', 'date'), name='unique_monthly_work_volume'),
        ),
    ]
