# Generated by Django 4.2.16 on 2025-04-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_passport', '0007_gallery_size'),
        ('construction_work', '0004_monthlyworkvolume_unique_monthly_work_volume'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyworkvolume',
            name='unique_monthly_work_volume',
        ),
        migrations.RemoveField(
            model_name='monthlyworkvolume',
            name='work_category',
        ),
        migrations.RemoveField(
            model_name='monthlyworkvolume',
            name='work_type',
        ),
        migrations.AddField(
            model_name='monthlyworkvolume',
            name='workk_volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction_work.workvolume'),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_passport.object'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_passport.object'),
        ),
        migrations.AlterField(
            model_name='workvolume',
            name='work_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction_work.workcategory'),
        ),
        migrations.AlterField(
            model_name='workvolume',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction_work.worktype'),
        ),
        migrations.AddConstraint(
            model_name='monthlyworkvolume',
            constraint=models.UniqueConstraint(fields=('workk_volume', 'date'), name='unique_monthly_work_volume'),
        ),
    ]
