# Generated by Django 4.2.16 on 2025-04-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_work', '0005_remove_monthlyworkvolume_unique_monthly_work_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyworkvolume',
            old_name='workk_volume',
            new_name='work_volume',
        ),
    ]
