# Generated by Django 4.2.16 on 2025-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_work', '0006_rename_workk_volume_monthlyworkvolume_work_volume'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyworkvolume',
            name='unique_monthly_work_volume',
        ),
        migrations.AddConstraint(
            model_name='monthlyworkvolume',
            constraint=models.UniqueConstraint(fields=('work_volume', 'date'), name='unique_monthly_work_volume'),
        ),
    ]
