# Generated by Django 4.2.16 on 2025-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_work', '0007_remove_monthlyworkvolume_unique_monthly_work_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='fact_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=32),
        ),
    ]
