# Generated by Django 4.2.16 on 2025-04-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('construction_work', '0008_workcategory_fact_amount_workcategory_plan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.currency'),
        ),
    ]
