# Generated by Django 4.2.16 on 2025-05-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='has_project_file',
            new_name='has_project_document',
        ),
    ]
