# Generated by Django 4.2.16 on 2025-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_rename_has_project_file_role_has_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='has_employee_communication',
            field=models.BooleanField(default=False),
        ),
    ]
