# Generated by Django 4.1.5 on 2024-12-13 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
        ('statement', '0002_rename_user_statementinformation_employee'),
        ('service', '0001_initial'),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('building_type', models.CharField(choices=[('cottage', 'Cottage'), ('flat', 'Flat'), ('office', 'Office'), ('industrial premises', 'Industrial Premises'), ('shop', 'Shop'), ('shopping mall', 'Shopping Mall')], max_length=255)),
                ('building_area', models.PositiveIntegerField()),
                ('service_total_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('equipment_total_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('payment_for_employment', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('payment_from_client', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=25)),
                ('discount_sum', models.DecimalField(decimal_places=2, max_digits=25)),
                ('service_data', models.JSONField(blank=True, null=True)),
                ('equipment_data', models.JSONField(blank=True, null=True)),
                ('equipment', models.ManyToManyField(null=True, to='resource.equipment')),
                ('service', models.ManyToManyField(blank=True, null=True, to='service.service')),
                ('service_category', models.ManyToManyField(blank=True, null=True, to='service.servicecategory')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_statements', to='statement.statement')),
            ],
            options={
                'verbose_name': 'OrderCheckList',
                'verbose_name_plural': 'OrderCheckLists',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
