# Generated by Django 4.1.5 on 2024-12-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklist_remove_service_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='equipment_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='service_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
