# Generated by Django 4.1.5 on 2024-12-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
        ('checklist', '0004_alter_checklist_equipment_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ('-id',), 'verbose_name': 'CheckList', 'verbose_name_plural': 'CheckLists'},
        ),
        migrations.AddField(
            model_name='checklist',
            name='equipment_category',
            field=models.ManyToManyField(null=True, to='resource.equipmentcategory'),
        ),
    ]
