# Generated by Django 4.1.5 on 2024-12-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_equipment_created_by_equipmentcategory_created_by_and_more'),
        ('checklist', '0006_checklist_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.timemeasurement'),
        ),
    ]
