# Generated by Django 4.1.5 on 2024-12-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_checklist_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='equipment_data',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='service_data',
        ),
    ]
