# Generated by Django 4.1.5 on 2024-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_remove_checklist_equipment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='service_dict',
            field=models.JSONField(default=dict),
        ),
    ]
