# Generated by Django 4.1.5 on 2024-12-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_checklist_service_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='service_data',
            field=models.JSONField(default=dict),
        ),
    ]
