# Generated by Django 4.1.5 on 2025-01-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_equipment_created_by_equipmentcategory_created_by_and_more'),
        ('checklist', '0010_checklist_service_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='service_dict',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.measurement'),
        ),
    ]
