# Generated by Django 4.1.5 on 2024-12-05 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_type', models.CharField(choices=[('corporate', 'Corporate'), ('individual', 'Individual')], max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='new', max_length=255)),
                ('inn', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StatementInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('discount_sum', models.DecimalField(decimal_places=2, default='0.00', max_digits=30)),
                ('duration_date', models.DateTimeField()),
                ('statament_comment', models.TextField(blank=True)),
                ('comment_for_employee', models.TextField(blank=True)),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statement.statement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement Information',
                'verbose_name_plural': 'Statement Informations',
                'ordering': ('-id',),
            },
        ),
    ]
