# Generated by Django 4.1.5 on 2024-12-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementinformation',
            old_name='user',
            new_name='employee',
        ),
    ]
