# Generated by Django 4.1.5 on 2024-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_statement_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='employee',
        ),
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='new', max_length=255),
        ),
    ]
