# Generated by Django 4.1.5 on 2024-12-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0005_remove_statement_employee_alter_statement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementinformation',
            name='employee',
        ),
        migrations.AddField(
            model_name='statement',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
