# Generated by Django 4.1.5 on 2024-12-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_country_created_by_district_created_by_and_more'),
        ('statement', '0006_remove_statementinformation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country'),
        ),
    ]
