# Generated by Django 4.2.16 on 2024-12-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcategorybutton',
            name='dashboard_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardbutton', verbose_name='Kinopka'),
        ),
        migrations.AddField(
            model_name='dashboardsubcategorybutton',
            name='dashboard_category_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardcategorybutton', verbose_name='Categoriya knopka'),
        ),
    ]
