# Generated by Django 4.2.16 on 2024-12-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardbutton',
            options={'verbose_name': 'Dashboard Button', 'verbose_name_plural': 'Asosiy Knopkalar'},
        ),
        migrations.AlterModelOptions(
            name='dashboardcategorybutton',
            options={'verbose_name': 'Dashboard Category Button', 'verbose_name_plural': 'Kategoriya Knopkalar'},
        ),
        migrations.AlterModelOptions(
            name='dashboardsubcategorybutton',
            options={'verbose_name': 'Dashboard Sub Category Button', 'verbose_name_plural': 'Obyekt nomlari'},
        ),
        migrations.AlterModelOptions(
            name='nextstagedocuments',
            options={'verbose_name': 'Keyingi hujjat', 'verbose_name_plural': 'Loyiha hujjatlari'},
        ),
        migrations.AlterModelOptions(
            name='projectdocumentation',
            options={'ordering': ['order'], 'verbose_name': 'Loyiha hujjati', 'verbose_name_plural': "Loyiha Bo'limlari"},
        ),
        migrations.AddField(
            model_name='projectdocumentation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
    ]
