# Generated by Django 4.2.16 on 2024-12-27 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_alter_dashboardbutton_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='calendar',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hujjat sanasi'),
        ),
        migrations.AddField(
            model_name='files',
            name='file_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hujjat Kodi'),
        ),
        migrations.AddField(
            model_name='files',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='is_forma',
            field=models.BooleanField(default=False, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='is_section',
            field=models.BooleanField(default=False, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='nextstagedocuments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti"),
        ),
        migrations.CreateModel(
            name='ProjectSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirigan vaqti")),
                ('next_stage_documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nextstagedocuments', verbose_name='Keyingi hujjat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Loyiha bo'limi",
                'verbose_name_plural': "Loyiha bo'limlari",
            },
        ),
        migrations.AddField(
            model_name='files',
            name='project_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectsections', verbose_name="Loyiha bo'limi"),
        ),
    ]
