# Generated by Django 4.1.5 on 2024-12-13 12:50

from django.db import migrations, models
import main.apps.service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.service.models.upload_service_images),
        ),
    ]
