# Generated by Django 4.1.5 on 2024-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_created_by_servicecategory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_data',
            field=models.JSONField(default=list),
        ),
    ]
