# Generated by Django 4.1.5 on 2024-12-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_service_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_data',
        ),
    ]
