# Generated by Django 4.2.16 on 2025-02-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0015_alter_documentfiles_options_and_more'),
        ('common', '0013_template_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('total_amount_year', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('vat', models.PositiveIntegerField()),
                ('work_volume_from_construction_beginning', models.PositiveIntegerField()),
                ('current_contract_amount_from_construction_beginning', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('work_volume_from_year_beginnging', models.PositiveIntegerField()),
                ('current_contract_amount_from_year_beginnging', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('work_volume_for_month', models.PositiveIntegerField()),
                ('current_contract_amount_for_month', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object')),
            ],
            options={
                'verbose_name': 'Form3',
                'verbose_name_plural': 'Form3',
                'db_table': 'form3',
                'ordering': ('-id',),
            },
        ),
    ]
