# Generated by Django 4.2.16 on 2025-01-31 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('equipment', '0003_alter_hydrostation_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('hydro_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.hydrostation')),
            ],
            options={
                'verbose_name': 'Industrial Equipment',
                'verbose_name_plural': 'Industrial Equipment',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IndustrialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity_code', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('delivered_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('delivered_in_percent', models.PositiveIntegerField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('remaining_in_percent', models.PositiveIntegerField()),
                ('expected_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=32)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('industrial_equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.industrialequipment')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.measurement')),
            ],
            options={
                'verbose_name': 'Industrial Asset',
                'verbose_name_plural': 'Industrial Assets',
                'ordering': ('-id',),
            },
        ),
    ]
