# Generated by Django 4.1.5 on 2024-12-06 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in stock', 'In Stock'), ('in use', 'In Use'), ('under repair', 'Under Repair'), ('booked', 'Booked'), ('deprecated', 'Deprecated')], max_length=255)),
                ('measurement_data', models.JSONField(default=dict)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipment')),
                ('equipment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipmentcategory')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.measurement')),
                ('time_measurement', models.ManyToManyField(to='resource.timemeasurement')),
            ],
            options={
                'verbose_name': 'Equipment Warehouse',
                'verbose_name_plural': 'Equipment Warehouses',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MaterialWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('total_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.material')),
                ('material_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.materialcategory')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.measurement')),
            ],
            options={
                'verbose_name': 'Material Warehouse',
                'verbose_name_plural': 'Material Warehouses',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='statementinformation',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='statementinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='StatementInformation',
        ),
    ]
