# Generated by Django 4.1.5 on 2025-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_equipment_created_by_equipmentcategory_created_by_and_more'),
        ('warehouse', '0003_equipmentwarehouse_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentwarehouse',
            name='time_measurement',
        ),
        migrations.RemoveField(
            model_name='equipmentwarehouse',
            name='measurement',
        ),
        migrations.AddField(
            model_name='equipmentwarehouse',
            name='measurement',
            field=models.ManyToManyField(to='resource.measurement'),
        ),
    ]
