# Generated by Django 4.2.16 on 2025-04-01 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.project_document.models.project_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object_passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Ish nomi')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Umumiy xarajat summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Construction Task',
                'verbose_name_plural': 'Project ConstructionT asks',
                'db_table': 'project_construction_task',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('is_forma', models.BooleanField(default=False, verbose_name='Forma')),
                ('is_section', models.BooleanField(default=False, verbose_name="Bo'lim")),
                ('is_file', models.BooleanField(default=False, verbose_name='Fayl yuklash')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_passport.object', verbose_name='Loyiha nomi')),
            ],
            options={
                'verbose_name': 'Project Document Type',
                'verbose_name_plural': 'Project Document Types',
                'db_table': 'project_document_type',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('project_document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_document.projectdocumenttype', verbose_name='Keyingi hujjat')),
            ],
            options={
                'verbose_name': 'Project Section',
                'verbose_name_plural': 'Project Sections',
                'db_table': 'project_section',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('calendar', models.DateField(blank=True, null=True)),
                ('file_code', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.apps.project_document.models.project_file.upload_document_files)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('project_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_document.projectdocumenttype', verbose_name='Next Stage Document')),
                ('project_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_document.projectsection', verbose_name='Project Section')),
            ],
            options={
                'verbose_name': 'Project Document File',
                'verbose_name_plural': 'Project Document Files',
                'db_table': 'project_document_file',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='Sarflangan summa')),
                ('date', models.DateField()),
                ('construction_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_construction_task', to='project_document.constructiontask', verbose_name='Qurilish ishlari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Expense',
                'verbose_name_plural': 'Monthly Expenses',
                'db_table': 'monthly_expense',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='constructiontask',
            name='project_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_document.projectdocumenttype'),
        ),
    ]
