# Generated by Django 4.2.16 on 2025-04-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsection',
            old_name='project_document_file',
            new_name='project_document_type',
        ),
    ]
