# Generated by Django 4.2.16 on 2025-04-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_document', '0002_rename_project_document_file_projectsection_project_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocumentfile',
            name='project_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_document.projectdocumenttype', verbose_name='Project Document type'),
        ),
    ]
