# Generated by Django 4.2.16 on 2024-11-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Obyekt nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
            ],
            options={
                'verbose_name': 'Obyekt nomi',
                'verbose_name_plural': 'Obyekt nomlari',
            },
        ),
        migrations.CreateModel(
            name='PrimaryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='primaryfiles', verbose_name='Fayllar')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Obyekt nomi')),
                ('file_code', models.CharField(max_length=30, verbose_name='Hujjat kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.primaryfiles', verbose_name='Fayllar')),
                ('object_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.objectname', verbose_name='Obyekt nomi')),
            ],
            options={
                'verbose_name': 'Birlamchi hujjat',
                'verbose_name_plural': 'Birlamchi hujjatlar',
            },
        ),
    ]
