# Generated by Django 4.2.16 on 2024-11-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_objectname_primaryfiles_primarydocuments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primaryfiles',
            options={'verbose_name': 'Birlamchi Fayl', 'verbose_name_plural': 'Birlamchi Fayllar'},
        ),
        migrations.RemoveField(
            model_name='primarydocuments',
            name='file',
        ),
        migrations.AddField(
            model_name='primaryfiles',
            name='primary_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.primarydocuments', verbose_name='Birlamchi hujjatlar'),
        ),
    ]
