# Generated by Django 4.2.16 on 2024-11-13 11:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_primaryfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryfiles',
            name='file',
            field=models.FileField(storage=main.models.OriginalNameFileSystemStorage(), upload_to='primaryfiles', verbose_name='Fayllar'),
        ),
    ]
