from django.urls import path
from main.apps.dashboard.views import document


urlpatterns = [
    path(
        'next-project-create/', 
        document.next_stage_document_create_api_view, 
        name='next_project_create'
    ),
    path(
        'next-project-list/<int:object>/', 
        document.next_stage_document_list_api_view,
        name='next_project_list'
    ),
    path(
        'next-project-update/<int:pk>/', 
        document.next_stage_document_update_api_view, 
        name='next_project_update'
    ),
    path(
        'next-project-delete/<int:pk>/', 
        document.next_stage_document_delete_api_view, 
        name='next_project_delete'
    ),
    path(
        'next-project-detail/<int:pk>/',
        document.next_stage_document_detail_api_view,
        name='next_project_detail'
    ),
    path(
        'file-create/', 
        document.file_create_api_view, 
        name='files-create'
    ),
    path(
        'file-list/<int:document>/', 
        document.file_list_api_view, 
        name='file_list'
    ),
    path(
        'file-update/<int:pk>/', 
        document.file_update_api_view, 
        name='files_update'
    ),
    path(
        'file-detail/<int:pk>/', 
        document.file_detail_api_view, 
        name='file_detail'
    ),
    path(
        'file-delete/<int:pk>/', 
        document.file_delete_api_view, 
        name='file_delete'
    ),
    path(
        'file-section-list/<int:pk>/', 
        document.get_files_section_api_view, 
        name='file_section_list'
    ),
    path(
        'project-section-list/<int:pk>/', 
        document.project_section_api_view, 
        name='project_sections_list'
    ),
    path(
        'project-section-create/', 
        document.project_section_api_view, 
        name='project_section_create'
    ),
    path(
        'project-section-update/<int:pk>/', 
        document.project_section_api_view, 
        name='project_section_update'
    ),
    path(
        'project-section-delete/<int:pk>/', 
        document.project_section_api_view, 
        name='project_section_delete'
    ),
    path(
        'file-search/', 
        document.file_search_api_view, 
        name='file_search'
    ),
    path(
        'all-statistics-data/', 
        document.all_statistics_data_api_view, 
        name='all_statistics_data'
    ),
]


