from django.urls import path
from ..views import document



urlpatterns = [
    path(
        'project-document/<int:pk>/', 
        document.project_document_api_view, 
        name='project-btn'
    ),
    path(
        'next-project-create/', 
        document.next_stage_document_create_api_view, 
        name='next_project_create'
    ),
    path(
        'next-project-list/<int:object>/', 
        document.next_stage_document_list_api_view,
        name='next-project-btn'
    ),
    path(
        'next-project-update/<int:pk>/', 
        document.next_stage_document_update_api_view, 
        name='next-patch-project-name'
    ),
    path(
        'next-project-delete/<int:pk>/', 
        document.next_stage_document_delete_api_view, 
        name='next_project_delete'
    ),
    path(
        'file-create/', 
        document.file_create_api_view, 
        name='files-create'
    ),
    path(
        'file-list/<int:document>/', 
        document.file_list_api_view, 
        name='get-files'
    ),
    path(
        'file-update/<int:pk>/', 
        document.file_update_api_view, 
        name='files-create'
    ),
    path(
        'file-detail/<int:pk>/', 
        document.file_detail_api_view, 
        name='get-files'
    ),
    path(
        'file-delete/<int:pk>/', 
        document.file_delete_api_view, 
        name='get-files'
    ),
    path(
        'file-section-list/<int:pk>/', 
        document.get_files_section_api_view, 
        name='get-files'
    ),
    path(
        'project-section-list/<int:pk>/', 
        document.project_section_api_view, 
        name='get-sections_list'
    ),
    path(
        'project-section-create/', 
        document.project_section_api_view, 
        name='post-sectioncreate'
    ),
    path(
        'project-section-update/<int:pk>/', 
        document.project_section_api_view, 
        name='patch-sections_update'
    ),
    path(
        'project-section-delete/<int:pk>/', 
        document.project_section_api_view, 
        name='patch-sections_delete'
    ),
    path(
        'file-search/', 
        document.file_search_api_view, 
        name='files-search'
    ),
    path(
        'get-doc/', 
        document.nested_data_api_view, 
        name='get-doc'
    ),
    path(
        'statistics-data/<int:pk>/', 
        document.object_password_detail_api_view, 
        name='post-doc'
    ),
    path(
        'all-statistics-data/', 
        document.statistical_data_api_view, 
        name='all-statistic'
    ),
]


