# Generated by Django 4.1.5 on 2024-12-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0006_checklist_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profitability_of_order', models.DecimalField(decimal_places=2, default='0.00', max_digits=25)),
                ('total_lead_time', models.CharField(blank=True, max_length=255, null=True)),
                ('order_comment', models.TextField(blank=True, null=True)),
                ('employee_note', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.checklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-id',),
            },
        ),
    ]
