# Generated by Django 4.2.16 on 2025-01-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('smr_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qurilish summasi')),
                ('equipment_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Uskunalar summasi')),
                ('investment_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Investitsiya summasi')),
                ('uge_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='UZBEKGIDRO summasi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Obyekt umumiy summasi')),
                ('total_power', models.CharField(blank=True, max_length=200, null=True, verbose_name='Umumiy quvvat')),
                ('category_btn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardcategorybutton', verbose_name='Kategoriya knopkalar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('main_btn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardbutton', verbose_name='Asosiy knopkalar')),
                ('project_documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectdocumentation', verbose_name="Obyekt bo'limi")),
                ('subcategory_btn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboardsubcategorybutton', verbose_name='Obyekt nomi')),
            ],
            options={
                'verbose_name': 'Obyekt paspord modeli',
                'verbose_name_plural': 'Obyekt paspordi',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='objpassword/files/%Y/%m/%d', verbose_name='Fayl')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('obj_password', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.objectspassword', verbose_name='Obyekt pasporti')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
                'ordering': ('-id',),
            },
        ),
    ]
