# Generated by Django 4.2.16 on 2025-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_objectspassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectspassword',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qurilish tuganlangan vaqti'),
        ),
        migrations.AddField(
            model_name='objectspassword',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qurilish boshlangan vaqti'),
        ),
    ]
