# Generated by Django 4.2.16 on 2025-01-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_files_created_by_alter_files_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectspassword',
            name='user',
        ),
    ]
