# Generated by Django 4.2.16 on 2025-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_objectspassword_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='files',
            table='main_files',
        ),
        migrations.AlterModelTable(
            name='objectspassword',
            table='objects_password',
        ),
    ]
