# Generated by Django 4.2.16 on 2025-02-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_object_objectcategory_objectsubcategory_and_more'),
        ('main', '0006_alter_files_table_alter_objectspassword_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectspassword',
            name='category_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectsubcategory', verbose_name='Kategoriya knopkalar'),
        ),
        migrations.AlterField(
            model_name='objectspassword',
            name='main_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.objectcategory', verbose_name='Asosiy knopkalar'),
        ),
        migrations.AlterField(
            model_name='objectspassword',
            name='subcategory_btn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.object', verbose_name='Obyekt nomi'),
        ),
    ]
