# Generated by Django 4.2.16 on 2025-03-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_objectspassword_category_btn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectspassword',
            name='category_btn',
        ),
        migrations.RemoveField(
            model_name='objectspassword',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='objectspassword',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='objectspassword',
            name='main_btn',
        ),
        migrations.RemoveField(
            model_name='objectspassword',
            name='project_documentation',
        ),
        migrations.RemoveField(
            model_name='objectspassword',
            name='subcategory_btn',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='ObjectsPassword',
        ),
    ]
