from django.urls import path
from . import views


urlpatterns = [
    path(
        'register/', 
        views.user_registration_api_view, 
        name='register'
    ),
    path(
        'send-otp/', 
        views.otp_sent_api_view, 
        name='sned-otp'
    ),
    path(
        'login/', 
        views.user_login_api_view, 
        name='login'
    ),
    path(
        'verify/', 
        views.user_otp_verify_api_view, 
        name='verify'
    ),
    path(
        "resend-otp/", 
        views.user_resend_otp_api_view, 
        name="resent-otp"
    ),
    path(
        'password-reset/', 
        views.password_reset_api_view, 
        name='password-reset'
    ),
    path(
        'password-reset-check/', 
        views.password_reset_check_view, 
        name='password-reset-check'
    ),
    path(
        'password-reset-confirm/', 
        views.password_reset_confirm_view, 
        name='password-reset-confirm'
    ),
    path(
        "detail/<int:pk>/", 
        views.user_retrieve_update_api_view, 
        name="user_detail"
    ),
    path(
        "update/<int:pk>/", 
        views.user_retrieve_update_api_view, 
        name="user_update"
    ),
    path(
        'list/', 
        views.user_list_view, 
        name='list'
    ),
]
