# Generated by Django 4.1.5 on 2024-12-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_for', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pickup_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in processing', 'In Processing'), ('decided', 'Decided'), ('under review', 'Under Review'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=255)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipment')),
                ('equipment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipmentcategory')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.material')),
                ('material_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.materialcategory')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.measurement')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_return_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_return_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Return',
                'verbose_name_plural': 'Resource Returns',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_for', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pickup_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in processing', 'In Processing'), ('decided', 'Decided'), ('under review', 'Under Review'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=255)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipment')),
                ('equipment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipmentcategory')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.material')),
                ('material_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.materialcategory')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.measurement')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_ruest_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_request_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Request',
                'verbose_name_plural': 'Resource Requests',
                'ordering': ('-id',),
            },
        ),
    ]
