# Generated by Django 4.1.5 on 2024-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcereturn',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=255),
        ),
    ]
