# Generated by Django 4.1.5 on 2024-12-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceflow', '0002_alter_resourcerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
