# Generated by Django 4.1.5 on 2024-12-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_equipment_created_by_equipmentcategory_created_by_and_more'),
        ('resourceflow', '0004_resourcerequest_created_by_resourcereturn_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipment'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.material'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='material_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.materialcategory'),
        ),
        migrations.AlterField(
            model_name='resourcereturn',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipment'),
        ),
        migrations.AlterField(
            model_name='resourcereturn',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='resourcereturn',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.material'),
        ),
        migrations.AlterField(
            model_name='resourcereturn',
            name='material_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.materialcategory'),
        ),
    ]
