# Generated by Django 4.1.5 on 2024-12-11 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resourceflow', '0002_alter_resourcerequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_notifications', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_notifications', to=settings.AUTH_USER_MODEL)),
                ('resource_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='resourceflow.resourcerequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material',
        ),
        migrations.RemoveField(
            model_name='service',
            name='material_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
